<a href="https://colab.research.google.com/github/JadenD5321/Summer-2022-Microcredential-/blob/main/Homework_2_Numpy_Exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPy Problems

____________

#### Import NumPy as np

In [ ]:
import numpy as np #a special library that is used particularly for sorting important information in data.

#### Create an array of 20 zeros 

In [ ]:
import numpy as np
array=np.zeros(20)# create an array of 20 zeros. 
print(array)



[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### Create an array of 10 ones

In [ ]:
import numpy as np
array=np.ones(10)# create an array of 10 ones. 
print(array)



[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


#### Create an array of 10 fives

In [ ]:
#used python classes as a reference
# https://numpy.org/doc/stable/reference/routines.array-creation.html
import numpy as np
array=np.ones(10)*5 # this function will print out an array of 10 fives in total 
print(array)



[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


#### Create an array of the integers from 10 to 50

In [ ]:
# used youtube as a reference to find how to declare even values in python
# https://numpy.org/doc/stable/reference/routines.array-creation.html
import numpy as np 
int= np.arange(10,51) # this wil basically return numbers between the range of 10,51. Once we do that we can print the integer.
print(int)






[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]


#### Create an array of all the even integers from 10 to 50

In [ ]:
# used youtube as a reference to find how to declare even values in python
# https://numpy.org/doc/stable/reference/routines.array-creation.html
import numpy as np 
int= np.arange(10,51,2)# this will print out even numbers between 10 and 51 and we will use the value 2 as the last number to make sure that the values are added by 2 each time.
print(int)




[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]


#### Create a 3x3 matrix with values ranging from 0 to 8

In [ ]:
# used a reference to find how to formulate matrixes statements in Python
# https://numpy.org/doc/stable/reference/routines.array-creation.html

import numpy as np
mat=np.arange(0,9).reshape(3,3) # print the range between 0-8. 
print(mat)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### Create a 3x3 identity matrix

In [ ]:
# used a reference to find how to formulate matrixes statements in Python
#https://numpy.org/doc/stable/reference/generated/numpy.ones_like.html
import numpy as np
mat=np.eye(3) # prints out a 3 by 3 identity matrix. numpy eye is another way to declare identity in python
print(mat)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

#### Use NumPy to generate a random number between 0 and 1

In [ ]:
import numpy as np
random_number= np.random.normal(0,1)
print(random_number)


1.8073881541738783


#### Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution

In [ ]:
import numpy as np 
random_number= np.random.rand(25)
print(random_number)


[0.46722351 0.3076402  0.73871105 0.30378031 0.70302776 0.43046849
 0.92161162 0.04717915 0.49008555 0.44176942 0.23293868 0.39335207
 0.93700078 0.70437465 0.88435599 0.33531205 0.92867633 0.13483919
 0.72177903 0.53346974 0.69300706 0.46939931 0.65464811 0.77223696
 0.69798952]


#### Create the following matrix:

In [ ]:
# create an array that begins from 0.01-1. 
import numpy as np
int= np.arange(0.01,1.01,0.01).reshape(10,10) # we have to set the range between 0.1-1. We will then have to reshape the dimensions to a 10 by 10 matrix. 
print(int)


[[0.01 0.02 0.03 0.04 0.05 0.06 0.07 0.08 0.09 0.1 ]
 [0.11 0.12 0.13 0.14 0.15 0.16 0.17 0.18 0.19 0.2 ]
 [0.21 0.22 0.23 0.24 0.25 0.26 0.27 0.28 0.29 0.3 ]
 [0.31 0.32 0.33 0.34 0.35 0.36 0.37 0.38 0.39 0.4 ]
 [0.41 0.42 0.43 0.44 0.45 0.46 0.47 0.48 0.49 0.5 ]
 [0.51 0.52 0.53 0.54 0.55 0.56 0.57 0.58 0.59 0.6 ]
 [0.61 0.62 0.63 0.64 0.65 0.66 0.67 0.68 0.69 0.7 ]
 [0.71 0.72 0.73 0.74 0.75 0.76 0.77 0.78 0.79 0.8 ]
 [0.81 0.82 0.83 0.84 0.85 0.86 0.87 0.88 0.89 0.9 ]
 [0.91 0.92 0.93 0.94 0.95 0.96 0.97 0.98 0.99 1.  ]]


#### Create an array of 20 linearly spaced points between 0 and 1:

In [ ]:
# use a reference to find how to declare linearly spaces in python
# https://numpy.org/doc/stable/reference/generated/numpy.linspace.html

import numpy as np
int= np.linspace(0, 1, 20) # this part will basically return 
print(int)


[0.         0.05263158 0.10526316 0.15789474 0.21052632 0.26315789
 0.31578947 0.36842105 0.42105263 0.47368421 0.52631579 0.57894737
 0.63157895 0.68421053 0.73684211 0.78947368 0.84210526 0.89473684
 0.94736842 1.        ]


## Numpy Indexing and Selection

Now you will be given a few matrices, and be asked to replicate the resulting matrix outputs:

In [ ]:
import numpy as np
#mat = np.arange(1,27).reshape(5,5)
mat = np.arange(1,28).reshape(9,3)
mat

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21],
       [22, 23, 24],
       [25, 26, 27]])

In [ ]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [ ]:
# https://www.delftstack.com/howto/python/print-matrix-python/
# https://pythonguides.com

array1 = np.arange(12, 16) #prints numbers between the range of 12-16
array2 = np.arange(17, 21) # prints numbers between the range of 17-21
array3 = np.arange(22, 26) # prints numbers between the range of 22-26

arr = np.concatenate([array1, array2, array3]) # we will have an array of 3 different declarations 
arr.reshape(3, 4) #  we will reshape its dimension to a 3 by 4.

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [ ]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [ ]:
# find a range that will priint between 20 and 21
array = np.arange(20, 21) # an array that prints a range between 20-21
print(array) # finally, it will print the array

[20]


In [ ]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [ ]:
import numpy as np
array = np.arange(21, 26)#an array that prints out between the range from 21-25
print(array) # finally, it will print the array

[21 22 23 24 25]


In [ ]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [ ]:
import numpy as np
array = np.arange(21, 26)#an array that prints out between the range from 21-25
print(array) # finally, it will print the array







[21 22 23 24 25]


### Now,

#### Get the sum of all the values in mat

In [ ]:
mat = np.arange(1,28).reshape(9,3)
print(mat)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]
 [19 20 21]
 [22 23 24]
 [25 26 27]]


#### Get the standard deviation of the values in mat

In [ ]:
# https://www.geeksforgeeks.org/python-statistics-stdev/

mat.std() # enables us to form our standard deviation method


2.581988897471611

#### Get the sum of all the columns in mat

In [ ]:
# https://www.geeksforgeeks.org/numpy-sum-in-python/
mat.sum(axis=1) # this will print the sum along the axis. 


array([ 3, 12, 21])

# Cheers!